version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    image: library-api
    container_name: library-api
    ports:
      - '80:80'
    env_file:
      - .env

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

    env_file:
      - .env
    ports:
      - '3306:3306'
