version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    image: library-web
    container_name: library-web
    ports:
      - '3000:3000'
    env_file:
      - .env.web

  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    image: library-api
    container_name: library-api
    ports:
      - '80:80'
    env_file:
      - .env
      - .env.example

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

    env_file:
      - .env
      - .env.example
    ports:
      - '3306:3306'
