version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=manager
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
