"""Initial migration

Revision ID: 1083ab177974
Revises: 
Create Date: 2023-12-28 16:03:23.974847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1083ab177974'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('borrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_at', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.Integer(), nullable=False),
    sa.Column('returned_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_book_id'), 'borrow', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrow_borrowed_at'), 'borrow', ['borrowed_at'], unique=False)
    op.create_index(op.f('ix_borrow_due_at'), 'borrow', ['due_at'], unique=False)
    op.create_index(op.f('ix_borrow_returned_at'), 'borrow', ['returned_at'], unique=False)
    op.create_index(op.f('ix_borrow_user_id'), 'borrow', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_user_id'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_returned_at'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_due_at'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_borrowed_at'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_book_id'), table_name='borrow')
    op.drop_table('borrow')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
