"""Fixed user borrows relationship

Revision ID: 6a7e0c4725fa
Revises: 4cf8341f0dd8
Create Date: 2023-12-29 10:07:59.108299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7e0c4725fa'
down_revision: Union[str, None] = '4cf8341f0dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
