#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${MYSQL_USER}" ]; then
    base_postgres_image_default_user='root'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi

# Ensure required environment variables are set
if [ -z "${MYSQL_PASSWORD}" ] || [ -z "${MYSQL_HOST}" ] || [ -z "${MYSQL_PORT}" ] || [ -z "${MYSQL_DATABASE}" ]; then
    echo "Environment variables MYSQL_PASSWORD, MYSQL_HOST, MYSQL_PORT, and MYSQL_DATABASE must be set."
    exit 1
fi

export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

mysql_ready() {
python << END
import sys
import pymysql

try:
    pymysql.connect(
        db="${MYSQL_DATABASE}",
        user="${MYSQL_USER}",
        passwd="${MYSQL_PASSWORD}",
        host="${MYSQL_HOST}",
        port=int("${MYSQL_PORT}")
    )
except pymysql.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done

>&2 echo 'MySQL is available'

exec "$@"
